# Generated by Django 3.2.2 on 2021-05-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_id',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
