# Generated by Django 3.2.2 on 2021-05-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('student', '0003_auto_20210511_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
