# Generated by Django 3.2.2 on 2021-05-11 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('student', '0004_student_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email_id',
            new_name='email',
        ),
    ]
