# Generated by Django 3.2.2 on 2021-05-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('student', '0009_choices_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='choices',
            field=models.ManyToManyField(to='student.Student'),
        ),
    ]
