# Generated by Django 3.2.2 on 2021-05-16 21:01

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('student', '0010_alter_profile_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', multiselectfield.db.fields.MultiSelectField(
                    choices=[(1, 'Value1'), (2, 'Value2'), (3, 'Value3'), (4, 'Value4'), (5, 'Value5')], max_length=3)),
            ],
        ),
    ]
